
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/people?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1qaz-xsw2
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: localhost
mybatis:
  type-aliases-package: com.tangliangying.domain
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8087

#redis配置

